# Generated by Django 3.1.4 on 2020-12-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='visit',
            name='si',
        ),
        migrations.AlterField(
            model_name='patient',
            name='bday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
