# Generated by Django 3.1.4 on 2020-12-28 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20201227_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patients.company'),
        ),
    ]
