# Generated by Django 3.1.4 on 2021-01-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20201228_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
